"use client";

import {
  CubeTransparentIcon,
  UserCircleIcon,
  CodeBracketSquareIcon,
  Square3Stack3DIcon,
  ChevronDownIcon,
  Cog6ToothIcon,
  InboxArrowDownIcon,
  LifebuoyIcon,
  PowerIcon,
  RocketLaunchIcon,
  Bars2Icon,
  ArrowLeftOnRectangleIcon,
  ChatBubbleLeftIcon,
  PaperAirplaneIcon,
  ShareIcon,
  EllipsisVerticalIcon,
} from "@heroicons/react/24/outline";

import {
  StarIcon,
  PhotoIcon,
  VideoCameraIcon,
  CalendarDaysIcon,
  NewspaperIcon,
  HeartIcon,
  HomeIcon,
  UserGroupIcon,
  PuzzlePieceIcon,
  BuildingStorefrontIcon,
  PencilSquareIcon,
  MagnifyingGlassIcon,
} from "@heroicons/react/24/solid";

export {
  CubeTransparentIcon,
  UserCircleIcon,
  CodeBracketSquareIcon,
  Square3Stack3DIcon,
  ChevronDownIcon,
  Cog6ToothIcon,
  InboxArrowDownIcon,
  LifebuoyIcon,
  PowerIcon,
  RocketLaunchIcon,
  Bars2Icon,
  ArrowLeftOnRectangleIcon,
  StarIcon,
  HeartIcon,
  ChatBubbleLeftIcon,
  PaperAirplaneIcon,
  ShareIcon,
  EllipsisVerticalIcon,
  PhotoIcon,
  VideoCameraIcon,
  CalendarDaysIcon,
  NewspaperIcon,
  HomeIcon,
  UserGroupIcon,
  PuzzlePieceIcon,
  BuildingStorefrontIcon,
  PencilSquareIcon,
  MagnifyingGlassIcon,
};
